# generated by datamodel-codegen:
#   filename:  artifact-reference.schema.json
#   timestamp: 2026-08-06T01:55:57+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class ArtifactType(StrEnum):
    cell = "cell"
    parameter = "parameter"
    model = "model"
    plot = "plot"
    conclusion = "conclusion"
    dataset = "dataset"
    standard = "standard"
    requirement = "requirement"
    document = "document"
    computation = "computation"


class LineRange(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    start: Annotated[int, Field(description="Starting line number (1-based, inclusive).", ge=1)]
    end: Annotated[int, Field(description="Ending line number (1-based, inclusive).", ge=1)]


class Location(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    file_path: Annotated[
        str | None,
        Field(
            alias="filePath",
            description="Path to the file containing this artifact, relative to the project root.",
        ),
    ] = None
    cell_id: Annotated[
        str | None,
        Field(
            alias="cellId",
            description="Identifier of the notebook cell, if the artifact is within a notebook.",
        ),
    ] = None
    line_range: Annotated[
        LineRange | None,
        Field(alias="lineRange", description="Line range within the file, if applicable."),
    ] = None
    uri: Annotated[
        AnyUrl | None,
        Field(
            description="URI to the artifact, if it is externally hosted or has a canonical address."
        ),
    ] = None


class Relationship(StrEnum):
    depends_on = "depends-on"
    informs = "informs"
    produced_by = "produced-by"
    validates = "validates"
    contradicts = "contradicts"


class ArtifactReference(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    id: Annotated[str, Field(description="Unique identifier for this artifact reference.")]
    artifact_type: Annotated[
        ArtifactType,
        Field(alias="artifactType", description="The type of artifact being referenced."),
    ]
    label: Annotated[str, Field(description="Human-readable name or label for this artifact.")]
    location: Annotated[
        Location | None,
        Field(
            description="Location information for this artifact. All fields are optional to accommodate different artifact types."
        ),
    ] = None
    relationship: Annotated[
        Relationship,
        Field(
            description="The relationship between the Judgment Point and this artifact. 'depends-on' means the artifact's correctness depends on the judgment. 'informs' means the artifact provides evidence for the judgment. 'produced-by' means the artifact was generated as a result of the judgment. 'validates' means the artifact validates the judgment's resolution. 'contradicts' means the artifact provides evidence against a particular alternative or the current resolution."
        ),
    ]
    description: Annotated[
        str | None,
        Field(
            description="Optional human-readable description of how this artifact relates to the Judgment Point."
        ),
    ] = None
