# generated by datamodel-codegen:
#   filename:  judgment-point.schema.json
#   timestamp: 2026-08-06T01:55:57+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from . import artifact_reference_schema


class Category(StrEnum):
    objective = "objective"
    framing = "framing"
    assumption = "assumption"
    method = "method"
    data = "data"
    parameter = "parameter"
    validation = "validation"
    interpretation = "interpretation"


class Status(StrEnum):
    candidate = "candidate"
    pending = "pending"
    investigating = "investigating"
    resolved = "resolved"
    delegated = "delegated"
    stale = "stale"
    reopened = "reopened"
    dismissed = "dismissed"


class Source(StrEnum):
    agent = "agent"
    rule = "rule"
    skill = "skill"
    tool = "tool"
    user = "user"
    dependency_change = "dependency-change"


class JudgmentTrigger(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    source: Annotated[Source, Field(description="What detected or initiated this candidate.")]
    description: Annotated[
        str, Field(description="Human-readable description of what triggered detection.")
    ]
    hard_trigger: Annotated[
        str | None,
        Field(
            alias="hardTrigger", description="If a hard trigger rule matched, which rule it was."
        ),
    ] = None
    rule_id: Annotated[
        str | None,
        Field(
            alias="ruleId", description="Identifier of the rule or policy that triggered detection."
        ),
    ] = None


class Dimensions(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    methodological_discretion: Annotated[int, Field(alias="methodologicalDiscretion", ge=0, le=3)]
    downstream_influence: Annotated[int, Field(alias="downstreamInfluence", ge=0, le=3)]
    uncertainty: Annotated[int, Field(ge=0, le=3)]
    consequence: Annotated[int, Field(ge=0, le=3)]
    reversibility: Annotated[int, Field(ge=0, le=3)]
    accountability_requirement: Annotated[int, Field(alias="accountabilityRequirement", ge=0, le=3)]


class InterventionLevel(StrEnum):
    trace = "trace"
    disclose = "disclose"
    pause = "pause"
    require_investigation = "require-investigation"


class MaterialityAssessment(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    score: Annotated[
        int,
        Field(
            description="Aggregate materiality score (sum of six dimensions, each 0-3).",
            ge=0,
            le=18,
        ),
    ]
    dimensions: Annotated[Dimensions, Field(description="Individual materiality dimension scores.")]
    detector_confidence: Annotated[
        float | None,
        Field(
            alias="detectorConfidence",
            description="Confidence of the detector in its assessment (0.0 to 1.0). Optional when assessment is manual.",
            ge=0.0,
            le=1.0,
        ),
    ] = None
    hard_trigger: Annotated[
        str | None,
        Field(
            alias="hardTrigger",
            description="If a hard trigger rule applied, overriding the score-based intervention.",
        ),
    ] = None
    intervention_level: Annotated[
        InterventionLevel | None,
        Field(
            alias="interventionLevel",
            description="The intervention level determined by the materiality score and applicable policies.",
        ),
    ] = None


class Source1(StrEnum):
    agent = "agent"
    user = "user"
    standard = "standard"
    prior_decision = "prior-decision"


class JudgmentAlternative(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    id: Annotated[
        str, Field(description="Unique identifier for this alternative within the Judgment Point.")
    ]
    label: Annotated[str, Field(description="Short label for this alternative.")]
    description: Annotated[
        str, Field(description="Detailed description of what this alternative entails.")
    ]
    tradeoffs: Annotated[
        str | None,
        Field(description="Known tradeoffs or consequences of selecting this alternative."),
    ] = None
    evidence_refs: Annotated[
        list[artifact_reference_schema.ArtifactReference] | None,
        Field(
            alias="evidenceRefs",
            description="References to evidence supporting or relevant to this alternative.",
        ),
    ] = None
    source: Annotated[
        Source1 | None, Field(description="Who or what proposed this alternative.")
    ] = None
    comparison_data: Annotated[
        dict[str, Any] | None,
        Field(
            alias="comparisonData",
            description="Structured data from a comparison calculation, if one was performed.",
        ),
    ] = None


class Mode(StrEnum):
    human = "human"
    collaborative = "collaborative"
    delegated = "delegated"
    rule = "rule"


class JudgmentAuthority(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    mode: Annotated[
        Mode,
        Field(
            description="How resolution authority is assigned. 'human' requires direct human decision. 'collaborative' involves human and agent working together. 'delegated' allows agent resolution under an explicit policy. 'rule' indicates resolution by an external standard or requirement."
        ),
    ]
    actor_id: Annotated[
        str | None,
        Field(
            alias="actorId", description="Identifier of the person or agent authorized to resolve."
        ),
    ] = None
    policy_id: Annotated[
        str | None,
        Field(
            alias="policyId",
            description="Identifier of the delegation policy that authorizes resolution, if applicable.",
        ),
    ] = None


class JudgmentResolution(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    selected_alternative_id: Annotated[
        str,
        Field(alias="selectedAlternativeId", description="Identifier of the chosen alternative."),
    ]
    rationale: Annotated[
        str, Field(description="Concise explanation of why this alternative was selected.")
    ]
    uncertainty: Annotated[
        list[str] | None,
        Field(description="Known uncertainties or unknowns at the time of resolution."),
    ] = []
    conditions: Annotated[
        list[str] | None,
        Field(
            description="Conditions applied to this resolution (e.g., 'Use source data covering 300-900 K')."
        ),
    ] = []
    validation_requirements: Annotated[
        list[str] | None,
        Field(
            alias="validationRequirements",
            description="Validation steps required after this resolution is applied.",
        ),
    ] = []
    resolved_at: Annotated[
        AwareDatetime, Field(alias="resolvedAt", description="When the resolution was recorded.")
    ]
    resolved_by: Annotated[
        str | None,
        Field(
            alias="resolvedBy", description="Identifier of the person or policy that resolved this."
        ),
    ] = None


class PreviousStatus(StrEnum):
    candidate = "candidate"
    pending = "pending"
    investigating = "investigating"
    resolved = "resolved"
    delegated = "delegated"
    stale = "stale"
    reopened = "reopened"
    dismissed = "dismissed"


class NewStatus(StrEnum):
    candidate = "candidate"
    pending = "pending"
    investigating = "investigating"
    resolved = "resolved"
    delegated = "delegated"
    stale = "stale"
    reopened = "reopened"
    dismissed = "dismissed"


class JudgmentRevision(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    timestamp: AwareDatetime
    previous_status: Annotated[PreviousStatus, Field(alias="previousStatus")]
    new_status: Annotated[NewStatus, Field(alias="newStatus")]
    reason: Annotated[str, Field(description="Why this revision occurred.")]
    previous_resolution: Annotated[
        JudgmentResolution | None,
        Field(
            alias="previousResolution",
            description="The resolution before this revision, if applicable.",
        ),
    ] = None
    actor_id: Annotated[
        str | None, Field(alias="actorId", description="Who initiated this revision.")
    ] = None


class JudgmentPoint(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    id: Annotated[str, Field(description="Unique identifier for this Judgment Point.")]
    project_id: Annotated[
        str,
        Field(
            alias="projectId",
            description="Identifier of the project this Judgment Point belongs to.",
        ),
    ]
    category: Annotated[
        Category,
        Field(description="The category of technical choice this Judgment Point represents."),
    ]
    question: Annotated[
        str,
        Field(
            description="The specific question being decided. Should describe the choice clearly enough that a reviewer can understand it without additional context."
        ),
    ]
    context: Annotated[
        str,
        Field(
            description="Background information explaining why this choice has arisen and what circumstances surround it."
        ),
    ]
    trigger: Annotated[
        JudgmentTrigger, Field(description="How this Judgment Point was detected or created.")
    ]
    materiality: Annotated[
        MaterialityAssessment,
        Field(
            description="The materiality assessment that determined the intervention level for this choice."
        ),
    ]
    status: Annotated[Status, Field(description="Current lifecycle status of this Judgment Point.")]
    alternatives: Annotated[
        list[JudgmentAlternative],
        Field(description="The defensible alternatives available for this choice."),
    ]
    evidence_refs: Annotated[
        list[artifact_reference_schema.ArtifactReference] | None,
        Field(
            alias="evidenceRefs",
            description="References to evidence, data, standards, or other artifacts that inform this choice.",
            validate_default=True,
        ),
    ] = []
    affected_artifact_ids: Annotated[
        list[str],
        Field(
            alias="affectedArtifactIds",
            description="Identifiers of artifacts (cells, parameters, models, plots, conclusions) that depend on this decision.",
        ),
    ]
    authority: Annotated[
        JudgmentAuthority,
        Field(description="Who or what is authorized to resolve this Judgment Point."),
    ]
    resolution: Annotated[
        JudgmentResolution | None,
        Field(description="The resolution of this Judgment Point, if one has been recorded."),
    ] = None
    validity_conditions: Annotated[
        list[str],
        Field(
            alias="validityConditions",
            description="Conditions under which this resolution remains valid. If any condition is no longer met, the resolution may become stale.",
        ),
    ]
    reopen_conditions: Annotated[
        list[str],
        Field(
            alias="reopenConditions",
            description="Conditions that should trigger a review of this decision.",
        ),
    ]
    revision_history: Annotated[
        list[JudgmentRevision] | None,
        Field(
            alias="revisionHistory",
            description="History of changes to this Judgment Point's resolution.",
            validate_default=True,
        ),
    ] = []
    created_at: Annotated[
        AwareDatetime,
        Field(alias="createdAt", description="When this Judgment Point was first created."),
    ]
    updated_at: Annotated[
        AwareDatetime,
        Field(alias="updatedAt", description="When this Judgment Point was last modified."),
    ]
