# generated by datamodel-codegen:
#   filename:  judgment-policy.schema.json
#   timestamp: 2026-08-06T01:55:57+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Category(StrEnum):
    objective = "objective"
    framing = "framing"
    assumption = "assumption"
    method = "method"
    data = "data"
    parameter = "parameter"
    validation = "validation"
    interpretation = "interpretation"


class TriggerSource(StrEnum):
    agent = "agent"
    rule = "rule"
    skill = "skill"
    tool = "tool"
    user = "user"
    dependency_change = "dependency-change"


class ArtifactType(StrEnum):
    cell = "cell"
    parameter = "parameter"
    model = "model"
    plot = "plot"
    conclusion = "conclusion"
    dataset = "dataset"
    standard = "standard"
    requirement = "requirement"
    document = "document"
    computation = "computation"


class PolicyScope(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    categories: Annotated[
        list[Category] | None,
        Field(
            description="Judgment Point categories this policy applies to. If omitted, applies to all categories."
        ),
    ] = None
    trigger_sources: Annotated[
        list[TriggerSource] | None,
        Field(
            alias="triggerSources",
            description="Trigger sources this policy applies to. If omitted, applies to all trigger sources.",
        ),
    ] = None
    artifact_types: Annotated[
        list[ArtifactType] | None,
        Field(
            alias="artifactTypes",
            description="Artifact types this policy applies to. If omitted, applies to all artifact types.",
        ),
    ] = None
    materiality_score_min: Annotated[
        int | None,
        Field(
            alias="materialityScoreMin",
            description="Minimum materiality score for this policy to apply. If omitted, no lower bound.",
            ge=0,
            le=18,
        ),
    ] = None
    materiality_score_max: Annotated[
        int | None,
        Field(
            alias="materialityScoreMax",
            description="Maximum materiality score for this policy to apply. If omitted, no upper bound.",
            ge=0,
            le=18,
        ),
    ] = None


class Intervention(StrEnum):
    trace = "trace"
    disclose = "disclose"
    pause = "pause"
    require_investigation = "require-investigation"


class DimensionThresholds(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    methodological_discretion: Annotated[
        int | None, Field(alias="methodologicalDiscretion", ge=0, le=3)
    ] = None
    downstream_influence: Annotated[int | None, Field(alias="downstreamInfluence", ge=0, le=3)] = (
        None
    )
    uncertainty: Annotated[int | None, Field(ge=0, le=3)] = None
    consequence: Annotated[int | None, Field(ge=0, le=3)] = None
    reversibility: Annotated[int | None, Field(ge=0, le=3)] = None
    accountability_requirement: Annotated[
        int | None, Field(alias="accountabilityRequirement", ge=0, le=3)
    ] = None


class RuleCondition(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    materiality_score_min: Annotated[
        int | None,
        Field(
            alias="materialityScoreMin",
            description="Minimum aggregate materiality score for this condition to match.",
            ge=0,
            le=18,
        ),
    ] = None
    materiality_score_max: Annotated[
        int | None,
        Field(
            alias="materialityScoreMax",
            description="Maximum aggregate materiality score for this condition to match.",
            ge=0,
            le=18,
        ),
    ] = None
    dimension_thresholds: Annotated[
        DimensionThresholds | None,
        Field(
            alias="dimensionThresholds",
            description="If any specified dimension meets or exceeds its threshold, this condition matches.",
        ),
    ] = None
    hard_trigger: Annotated[
        str | None,
        Field(
            alias="hardTrigger",
            description="A hard trigger rule name. If the Judgment Point was created by this hard trigger, the condition matches regardless of score.",
        ),
    ] = None
    categories: Annotated[
        list[Category] | None,
        Field(
            description="If specified, the Judgment Point's category must be in this list for the condition to match."
        ),
    ] = None
    expression: Annotated[
        str | None,
        Field(
            description="An optional free-form expression for advanced condition matching. Implementations may support a domain-specific language for complex conditions."
        ),
    ] = None


class Mode(StrEnum):
    human = "human"
    collaborative = "collaborative"
    delegated = "delegated"
    rule = "rule"


class AuthorityOverride(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    mode: Annotated[Mode, Field(description="The authority mode to apply when this rule matches.")]
    actor_id: Annotated[
        str | None,
        Field(alias="actorId", description="Specific actor to assign authority to, if applicable."),
    ] = None
    policy_id: Annotated[
        str | None,
        Field(
            alias="policyId",
            description="Delegation policy identifier, if the mode is 'delegated'.",
        ),
    ] = None


class ExcludedCategory(StrEnum):
    objective = "objective"
    framing = "framing"
    assumption = "assumption"
    method = "method"
    data = "data"
    parameter = "parameter"
    validation = "validation"
    interpretation = "interpretation"


class DelegationConditions(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    allowed: Annotated[
        bool | None, Field(description="Whether delegation is permitted at all for this rule.")
    ] = False
    max_materiality_score: Annotated[
        int | None,
        Field(
            alias="maxMaterialityScore",
            description="Maximum materiality score for which delegation is allowed.",
            ge=0,
            le=18,
        ),
    ] = None
    required_confidence: Annotated[
        float | None,
        Field(
            alias="requiredConfidence",
            description="Minimum detector confidence required for delegation (0.0 to 1.0).",
            ge=0.0,
            le=1.0,
        ),
    ] = None
    excluded_categories: Annotated[
        list[ExcludedCategory] | None,
        Field(
            alias="excludedCategories",
            description="Categories for which delegation is never permitted, even if other conditions are met.",
        ),
    ] = None
    requires_prior_human_resolution: Annotated[
        bool | None,
        Field(
            alias="requiresPriorHumanResolution",
            description="If true, delegation is only allowed if a materially similar Judgment Point was previously resolved by a human.",
        ),
    ] = False
    audit_required: Annotated[
        bool | None,
        Field(
            alias="auditRequired",
            description="If true, delegated resolutions must be flagged for subsequent human audit.",
        ),
    ] = True


class PolicyRule(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    id: Annotated[str, Field(description="Unique identifier for this rule within the policy.")]
    condition: Annotated[
        RuleCondition,
        Field(description="The condition that must be satisfied for this rule to apply."),
    ]
    intervention: Annotated[
        Intervention,
        Field(
            description="The intervention level to apply when this rule matches. 'trace' logs the decision silently. 'disclose' surfaces the decision to the user without blocking. 'pause' halts execution until the decision is resolved. 'require-investigation' halts execution and mandates structured comparison of alternatives before resolution."
        ),
    ]
    authority_override: Annotated[
        AuthorityOverride | None,
        Field(
            alias="authorityOverride",
            description="Optional override to the default authority mode when this rule matches.",
        ),
    ] = None
    delegation_conditions: Annotated[
        DelegationConditions | None,
        Field(
            alias="delegationConditions",
            description="Conditions under which automated or delegated resolution is permitted for this rule.",
        ),
    ] = None
    description: Annotated[
        str | None, Field(description="Human-readable description of what this rule does and why.")
    ] = None


class JudgmentPolicy(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    id: Annotated[str, Field(description="Unique identifier for this policy.")]
    project_id: Annotated[
        str,
        Field(alias="projectId", description="Identifier of the project this policy belongs to."),
    ]
    name: Annotated[str, Field(description="Human-readable name for this policy.")]
    description: Annotated[
        str,
        Field(description="Detailed description of what this policy governs and why it exists."),
    ]
    scope: Annotated[
        PolicyScope,
        Field(
            description="Defines which Judgment Points this policy applies to, based on categories, trigger sources, artifact types, or materiality thresholds."
        ),
    ]
    rules: Annotated[
        list[PolicyRule],
        Field(
            description="Ordered list of rules within this policy. Rules are evaluated in order; the first matching rule determines the outcome.",
            min_length=1,
        ),
    ]
    priority: Annotated[
        int,
        Field(
            description="Precedence ordering for this policy. Lower numbers indicate higher priority. When multiple policies match a Judgment Point, the one with the lowest priority value takes precedence.",
            ge=0,
        ),
    ]
    enabled: Annotated[
        bool,
        Field(
            description="Whether this policy is currently active. Disabled policies are retained for audit purposes but are not evaluated."
        ),
    ]
    created_at: Annotated[
        AwareDatetime, Field(alias="createdAt", description="When this policy was first created.")
    ]
    updated_at: Annotated[
        AwareDatetime, Field(alias="updatedAt", description="When this policy was last modified.")
    ]
