# generated by datamodel-codegen:
#   filename:  judgment-event.schema.json
#   timestamp: 2026-08-06T01:55:57+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class EventType(StrEnum):
    created = "created"
    promoted = "promoted"
    investigation_started = "investigation-started"
    resolution_recorded = "resolution-recorded"
    delegated = "delegated"
    dismissed = "dismissed"
    reopened = "reopened"
    marked_stale = "marked-stale"
    dependency_changed = "dependency-changed"
    artifact_linked = "artifact-linked"
    artifact_unlinked = "artifact-unlinked"
    alternative_added = "alternative-added"
    comparison_requested = "comparison-requested"
    comparison_completed = "comparison-completed"
    validity_condition_changed = "validity-condition-changed"


class ActorType(StrEnum):
    user = "user"
    agent = "agent"
    system = "system"
    policy = "policy"


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    correlation_id: Annotated[
        str | None,
        Field(
            alias="correlationId",
            description="Identifier to correlate this event with other events in the same logical operation.",
        ),
    ] = None
    session_id: Annotated[
        str | None,
        Field(
            alias="sessionId",
            description="Identifier of the user or agent session during which this event occurred.",
        ),
    ] = None
    tool_name: Annotated[
        str | None,
        Field(
            alias="toolName",
            description="Name of the tool or skill that was executing when this event occurred.",
        ),
    ] = None
    policy_id: Annotated[
        str | None,
        Field(
            alias="policyId",
            description="Identifier of the policy that governed this event, if applicable.",
        ),
    ] = None
    previous_status: Annotated[
        str | None,
        Field(alias="previousStatus", description="The Judgment Point's status before this event."),
    ] = None
    new_status: Annotated[
        str | None,
        Field(alias="newStatus", description="The Judgment Point's status after this event."),
    ] = None
    notes: Annotated[
        str | None, Field(description="Free-form notes or additional context about this event.")
    ] = None


class JudgmentEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: Annotated[str, Field(description="Unique identifier for this event.")]
    judgment_point_id: Annotated[
        str,
        Field(
            alias="judgmentPointId",
            description="Identifier of the Judgment Point this event belongs to.",
        ),
    ]
    project_id: Annotated[
        str,
        Field(alias="projectId", description="Identifier of the project this event belongs to."),
    ]
    event_type: Annotated[
        EventType,
        Field(
            alias="eventType",
            description="The type of lifecycle event. 'created' indicates initial detection as a candidate. 'promoted' indicates the candidate was promoted to a pending Judgment Point. 'investigation-started' indicates structured investigation of alternatives has begun. 'resolution-recorded' indicates a resolution was recorded. 'delegated' indicates resolution authority was delegated. 'dismissed' indicates the Judgment Point was dismissed as not requiring a decision. 'reopened' indicates a previously resolved or dismissed Judgment Point was reopened. 'marked-stale' indicates conditions have changed such that the resolution may no longer be valid. 'dependency-changed' indicates an upstream dependency has changed. 'artifact-linked' indicates an artifact was linked to this Judgment Point. 'artifact-unlinked' indicates an artifact was unlinked from this Judgment Point. 'alternative-added' indicates a new alternative was added. 'comparison-requested' indicates a structured comparison of alternatives was requested. 'comparison-completed' indicates a structured comparison of alternatives was completed. 'validity-condition-changed' indicates a validity condition was added, removed, or modified.",
        ),
    ]
    timestamp: Annotated[
        AwareDatetime,
        Field(
            description="When this event occurred. Events are ordered by timestamp within a Judgment Point's lifecycle."
        ),
    ]
    actor_id: Annotated[
        str,
        Field(
            alias="actorId",
            description="Identifier of the user, agent, system component, or policy that caused this event.",
        ),
    ]
    actor_type: Annotated[
        ActorType,
        Field(
            alias="actorType",
            description="The type of actor that caused this event. 'user' is a human user. 'agent' is an AI agent or assistant. 'system' is an automated system component. 'policy' is an automated policy engine applying rules.",
        ),
    ]
    payload: Annotated[
        dict[str, Any] | None,
        Field(
            description="Event-specific data. The structure of the payload depends on the eventType. For 'created', this may include the initial trigger and materiality assessment. For 'resolution-recorded', this includes the resolution details. For 'artifact-linked', this includes the artifact reference."
        ),
    ] = None
    metadata: Annotated[
        Metadata | None,
        Field(
            description="Optional additional context about this event. Metadata fields are not part of the core event model but provide useful information for debugging, auditing, and analysis."
        ),
    ] = None
