# generated by datamodel-codegen:
#   filename:  judgment-resolution.schema.json
#   timestamp: 2026-08-06T01:55:57+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ResolutionType(StrEnum):
    direct_human = "direct-human"
    collaborative = "collaborative"
    delegated = "delegated"
    rule_based = "rule-based"
    inherited = "inherited"


class JudgmentResolution(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="forbid",
    )
    selected_alternative_id: Annotated[
        str,
        Field(
            alias="selectedAlternativeId",
            description="Identifier of the chosen alternative from the Judgment Point's alternatives list.",
        ),
    ]
    rationale: Annotated[
        str,
        Field(
            description="Concise explanation of why this alternative was selected. Should be substantive enough for a reviewer to understand the reasoning without needing to reconstruct the original context."
        ),
    ]
    uncertainty: Annotated[
        list[str] | None,
        Field(
            description="Known uncertainties or unknowns at the time of resolution. Each entry describes a specific area where information was incomplete or where the outcome is not fully predictable."
        ),
    ] = []
    conditions: Annotated[
        list[str] | None,
        Field(
            description="Conditions or constraints applied to this resolution. These are specific requirements that bound how the resolution should be implemented (e.g., 'Use source data covering 300-900 K', 'Re-evaluate if sample size exceeds 10,000')."
        ),
    ] = []
    validation_requirements: Annotated[
        list[str] | None,
        Field(
            alias="validationRequirements",
            description="Validation steps required after this resolution is applied. Each entry describes a check or test that must be performed to confirm the resolution produces acceptable results.",
        ),
    ] = []
    resolved_at: Annotated[
        AwareDatetime, Field(alias="resolvedAt", description="When the resolution was recorded.")
    ]
    resolved_by: Annotated[
        str | None,
        Field(
            alias="resolvedBy",
            description="Identifier of the person, agent, or policy that recorded this resolution.",
        ),
    ] = None
    resolution_type: Annotated[
        ResolutionType,
        Field(
            alias="resolutionType",
            description="How this resolution was produced. 'direct-human' means a human made the decision without AI input. 'collaborative' means a human decided after reviewing AI-generated analysis or recommendations. 'delegated' means an agent resolved under an explicit delegation policy. 'rule-based' means the resolution was determined by a predefined rule or standard. 'inherited' means the resolution was carried over from a prior decision on a materially similar Judgment Point.",
        ),
    ]
    information_presented: Annotated[
        list[str] | None,
        Field(
            alias="informationPresented",
            description="Descriptions of what information was shown to the decision-maker before the resolution was recorded. This supports accountability by documenting the informational basis of the decision.",
        ),
    ] = []
    alternatives_considered: Annotated[
        list[str],
        Field(
            alias="alternativesConsidered",
            description="Identifiers of all alternatives that were reviewed before making this resolution. Must include at least the selected alternative.",
        ),
    ]
    initial_position: Annotated[
        str | None,
        Field(
            alias="initialPosition",
            description="The decision-maker's stated position before seeing AI recommendations or structured comparison data. Capturing this supports detection of anchoring bias and ensures the record reflects independent judgment.",
        ),
    ] = None
    recommendation_shown: Annotated[
        bool,
        Field(
            alias="recommendationShown",
            description="Whether an AI-generated recommendation was displayed to the decision-maker before resolution. This field is critical for bias-awareness: when true, the resolution should be evaluated with awareness that the recommendation may have influenced the decision.",
        ),
    ]
